### PR TITLE
Breakfast

### PR DESCRIPTION
**Pull request by albirch**
## 🎯 Objective

_Note why you're making this change and any relevant issues_
Moving breakfast to main branch

## 🛠️ Changes made
started the recipe and completed 
_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 
@Joy9251 
@lttlfld 
_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by albirch** [comment]
I removed test

**Comment by Joy9251** [comment]
Did we check the allergy issue?

**Comment by julianagensh** [comment]
Yes @Joy9251, I made sure to include an allergy warning at the bottom of this recipe. See the notes section.

**Comment by lttlfld** [comment]
I approve of this pull request

**Comment by Joy9251** [comment]
Can we update the serving size to 3? @johnnybt1

**Comment by johnnybt1** [comment]
> Can we update the serving size to 3? @johnnybt1

of course!

**Comment by Joy9251** [comment]
> > Can we update the serving size to 3? @johnnybt1
> 
> of course!

Cool! Will approve

**Comment by olgaklinger86** [comment]
Good work, team!

**Review by Joy9251 — COMMENTED** [review]
I approve

**Pull request merged**
