### PR TITLE
Breakfast 2

### PR DESCRIPTION
**Pull request by olgaklinger86**
## 🎯 Objective

_Note why you're making this change and any relevant issues_

Need to merge this branch with the main branch to finalize, as changes have been approved.

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

New version of breakfast recipe with all req'd changes.

## 👥 Who needs to review this Pull Request? 

@julianagensh  and @Joy9251 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by olgaklinger86** [comment]
Breakfast smoothie recipe finally looks good to go! If @julianagensh and @Joy9251 can comment/approve, we'll be done!

**Review by Joy9251 — COMMENTED** [review]
Looks good! It seems that all the issues are addressed

**Review by Joy9251 — APPROVED** [review]

**Comment by julianagensh** [comment]
Looks good to me too--great work team!

**Review by julianagensh — APPROVED** [review]
Approve the merging of this breakfast recipe.

**Pull request merged**
