### PR TITLE
4 dinner cherry tomato pasta

### LINKED ISSUE #4: Dinner: Cherry Tomato Pasta
## 💬 Discussion topic

Let's make a cherry tomato pasta

## ❗ Potential issues

-How much should we make?
-How long does it take to make the recipe 
-Do we have the equipment necessary?
-Allergies

## 👥 People
@lttlfld to list ingredients
@johnnybt1 to list time to make this recipe
@julianagensh to create instructions
@olgaklinger86 to make sure no one will have allergic reaction
@Joy9251 and @albirch to approve this project, as they are our bo$$e$

## 📃 Details

Acceptance Criteria:

- Clearly organized recipe
- Ingredients
- Instructions
- Time to make
- Make sure to list allergy warnings

Operation time to create this recipe on Github
- Medium project

### PR DESCRIPTION
**Pull request by johnnybt1**
## 🎯 Objective

_Note why you're making this change and any relevant issues_

## 🛠️ Changes made

_Note what you actual changes you're proposing_ 

## 👥 Who needs to review this Pull Request? 

_@mention some teammates to review your work._
_Pull Requests should include commits from each member of your group._

### CODE REVIEW

**Comment by johnnybt1** [comment]
we had breakfast in dinner, but had to delete dinner to resolve conflict, so now we have only breakfast in dinner...I think

**Comment by albirch** [comment]
I still see dinner recipe

**Review by Joy9251 — COMMENTED** [review]
It looks good!

**Comment by olgaklinger86** [comment]
Pasta is my favorite! Can we make sure it's indented properly?

**Comment by johnnybt1** [comment]
> I still see dinner recipe

oh good, thought we were going to have smoothies for dinner

**Review by Joy9251 — APPROVED** [review]
We deleted the right info at the right file.

**Comment by julianagensh** [comment]
Yummy, good job team!

**Comment by albirch** [comment]
Approved!

**Comment by olgaklinger86** [comment]
Looking good, I approve

**Pull request merged**
