### PR TITLE
3 lunch recipe white bean soup

### LINKED ISSUE #3: Lunch Recipe: White Bean Soup
## 💬 Discussion topic

Let's have white bean soup for lunch because it's healthy!

## ❗ Potential issues

-Do we have the equipment necessary?
-Allergies
-Do we have time to make this?
-What ingredients do I need to buy?

## 👥 People to consult

@lttlfld and @olgaklinger86 to make recipe clearly organized
@julianagensh to list ingredients
@albirch to create instructions
@johnnybt1 to list time to make this recipe
@Joy9251 to make sure no one will have allergic reaction

@julianagensh and @albirch to approve this project, as they are our bo$$e$

## 📃 Details

Acceptance Criteria:

Clearly organized recipe
Ingredients
Instructions
Time to make
Make sure to list allergy warnings

Operation time to create this recipe on Github:

Medium project

### PR DESCRIPTION
**Pull request by olgaklinger86**
## 🎯 Objective

Merge lunch recipe branch to main branch because ingredient changes are complete.

## 🛠️ Changes made

Ingredients, allergy warning, notes, steps/instructions, tips all added.

## 👥 Who needs to review this Pull Request? 

@julianagensh and @albirch are reiewing.

### CODE REVIEW

**Comment by olgaklinger86** [comment]
Soup's lookin' good!

**Comment by julianagensh** [comment]
@Joy9251 we need to add allergy warnings to this lunch recipe.

**Comment by Joy9251** [comment]
> @Joy9251 we need to add allergy warnings to this lunch recipe.

updated! Thanks for the reminder!

**Comment by olgaklinger86** [comment]
Thanks for catching that!

**Comment by albirch** [comment]
I am good with the changes

**Comment by julianagensh** [comment]
Thumbs up from me--great work team!

**Pull request merged**
